import { useQuery, useMutation } from "@tanstack/react-query"
import { createClient } from "@/lib/supabase"
import { useDemoStore } from "@/lib/demo-store"
import { Insight } from "@/types"

const isDemoMode = process.env.NEXT_PUBLIC_DEMO_MODE === 'true'

export function useInsights() {
  const { knowledgeItems } = useDemoStore()

  const insightsQuery = useQuery({
    queryKey: ["insights"],
    queryFn: async () => {
      // Demo mode: return mock insights based on knowledge items
      if (isDemoMode) {
        const insights: Insight[] = [
          {
            id: 'i1',
            user_id: 'demo-user',
            title: 'Your Knowledge at a Glance',
            summary: `You have ${knowledgeItems.length} knowledge items. Your recent focus seems to be on projects and learning.`,
            date: new Date().toISOString().split('T')[0],
            insight_type: 'daily_summary',
            items: knowledgeItems.slice(0, 3).map(item => ({
              type: item.content_type,
              title: item.title,
              relevance: 0.9,
            })),
            created_at: new Date().toISOString(),
          },
          {
            id: 'i2',
            user_id: 'demo-user',
            title: 'Connections Found',
            summary: 'Your notes on "AI Assistant" and "Next.js 16 Features" share common themes around technology.',
            date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
            insight_type: 'connection',
            items: [
              { type: 'note', title: 'Project Ideas: AI Assistant', relevance: 0.85 },
              { type: 'note', title: 'Research: Next.js 16 Features', relevance: 0.75 },
            ],
            created_at: new Date(Date.now() - 86400000).toISOString(),
          },
        ]
        return insights
      }

      // Real mode: fetch from Supabase
      const supabase = createClient()
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) throw new Error("Not authenticated")

      const { data, error } = await supabase
        .from("insights")
        .select("*")
        .eq("user_id", user.id)
        .order("created_at", { ascending: false })
        .limit(20)

      if (error) throw error
      return data as Insight[]
    },
  })

  const generateMutation = useMutation({
    mutationFn: async (type: "daily_summary" | "connection" | "spark") => {
      // Demo mode: return mock insight
      if (isDemoMode) {
        const mockInsight: Insight = {
          id: `demo-insight-${Date.now()}`,
          user_id: 'demo-user',
          date: new Date().toISOString().split('T')[0],
          title: type === 'daily_summary' ? 'Daily Summary' : type === 'connection' ? 'New Connection Found' : 'Spark of Inspiration',
          summary: 'This is a demo insight. In production, this would be generated by AI based on your knowledge items.',
          insight_type: type,
          items: [],
          created_at: new Date().toISOString(),
        }
        return mockInsight
      }

      // Real mode: call API
      const response = await fetch("/api/insights", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ type }),
      })

      const data = await response.json()
      if (data.error) throw new Error(data.error)
      return data.insight as Insight
    },
  })

  return {
    insights: insightsQuery.data,
    isLoading: isDemoMode ? false : insightsQuery.isLoading,
    error: isDemoMode ? null : insightsQuery.error,
    generateInsight: generateMutation.mutateAsync,
    isGenerating: generateMutation.isPending,
  }
}
